language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - pytest --cov tinycards-python-api
after_success:
  - coveralls
deploy:
  provider: pypi
  user: floscha
  password:
    secure: "fGNlMnLPdmIUulX2oNQF4a78Utfce2Dg9Sld/EAyBkM5B0kz80SxrXHkOOdIfDyOwSnAJAf2nSJcGmbAH2ZfYdG6Bmyhl5ZgH8OzTqUbZdzym2gPKQ2z+aaqxZ0tXrEBMNm6oMhFAG47aPKWTiWynVa4KpYQnl6nfWxPZvdgK60a8WNXKnjgQd8/h6bW1SDb6wY/dy+TTQ5RGxqsqkwG9TuhmGCzopBLdnLhwHL3fr0XivWTqxxBOWvt5GS404X7MrGfjYvDQUYcaUfqDSvNXS5TNYMPBIfB2RumgLXqc7Z88vZ1j26yG364N/9WOOLINOxXkLVCl3+RRyzXGk30vQCN6VSVQe9vXH8XsrTZBepArOm2tYf2Su785pKQjQiC5KwsbWBbj9dS187yewXe5dL9mvwOTOxlzyiXJRgbt40htfYcnx6JrNc1sLxN9QYcGHhazkGh1FzAAcZL7RBazO86zMTP5zZuF16gI7kkMQdI0cj5y8LuN0T1TQ8pehH8kKkqVneJSGtKsLbRB6Sw6dl1iAyH2qKMcvpPk/kM+LzC8NGm1m4gGOBcLKgdb42xQSb5sq7hQrO4Zu0wt1xm3gpmpXD6Ncdx17ngQd1KqSCChoEe/ZWMks/j6wf7tQP/+vShQvyF461UzTYdbJdRijz0WKYDECIaAKsm2cN8SOc="
