language: python
python:
  - '3.6'
install:
  - pip install -e .
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - pytest --cov
after_success:
  - coveralls
deploy:
  provider: pypi
  user: floscha
  password:
    secure: fGNlMnLPdmIUulX2oNQF4a78Utfce2Dg9Sld/EAyBkM5B0kz80SxrXHkOOdIfDyOwSnAJAf2nSJcGmbAH2ZfYdG6Bmyhl5ZgH8OzTqUbZdzym2gPKQ2z+aaqxZ0tXrEBMNm6oMhFAG47aPKWTiWynVa4KpYQnl6nfWxPZvdgK60a8WNXKnjgQd8/h6bW1SDb6wY/dy+TTQ5RGxqsqkwG9TuhmGCzopBLdnLhwHL3fr0XivWTqxxBOWvt5GS404X7MrGfjYvDQUYcaUfqDSvNXS5TNYMPBIfB2RumgLXqc7Z88vZ1j26yG364N/9WOOLINOxXkLVCl3+RRyzXGk30vQCN6VSVQe9vXH8XsrTZBepArOm2tYf2Su785pKQjQiC5KwsbWBbj9dS187yewXe5dL9mvwOTOxlzyiXJRgbt40htfYcnx6JrNc1sLxN9QYcGHhazkGh1FzAAcZL7RBazO86zMTP5zZuF16gI7kkMQdI0cj5y8LuN0T1TQ8pehH8kKkqVneJSGtKsLbRB6Sw6dl1iAyH2qKMcvpPk/kM+LzC8NGm1m4gGOBcLKgdb42xQSb5sq7hQrO4Zu0wt1xm3gpmpXD6Ncdx17ngQd1KqSCChoEe/ZWMks/j6wf7tQP/+vShQvyF461UzTYdbJdRijz0WKYDECIaAKsm2cN8SOc=
env:
  global:
    - TINYCARDS_IDENTIFIER=njam-test
    - TINYCARDS_PASSWORD=gRaVeATiod
    - secure: gL83Z1BCqlU7Sq11GeOYbzcAo6kpaD/OlFkudlI8rJCFG9/6CS9pzIr8CF+HiTGehB3JMGto6+ETPJios3SLZuPYWCSXyaoMf8wrJ/TkAjy91P9D3dh/Y4xvwY91BOye9OG848HnOrtxu0Vxh72GtWhoMvMdZvyw0HOfJKij/eUXS+YtN9ivg/4eLhbkZEJjtDFzZoOb6y73KgaSB2BaRCwhPt/d173vLlZeHWXCglf/Wmf5fe7yKozKLRR3o5ytNm1xdnU6Ep4hs8b8Piz9N/NKmTtScUYTO9EZZXEqttg6qt7tj9L6udmSv/SZ10RUMGf5E90MCVEcXOY7HnQyTN2uxy5gjx/z6nePXFSPG5jRScW7q35G5XdK/RsQznex+y+dLOkyPVuujXimK5KUvzyGKOc3FrhTkvAadcZhx/P+1TEChVRSZPGAZ0sZVUvCbvtyROT2kf7dmtYU1o9qqBeLJEq4D8kNqwjIp05G5jo6mKjWUNQm3VFu8/JaD7wTJLe0yJVOYwqzTQYD8vw2kZUgstH24yltlPdrLHxx48wIhqibXUk0KyjuH8vKEiSRkXFw7d08da1lJqhTxI1Am7nXmcWPjqmyqcKHvajMFlzuTSfquhxuBdN+K5xMz2+wzJhOBjvat5K54KVTJJYoVYWDXZydPJ6habZ5ozQHD+o=
    - secure: syC6+YUxU89eO8i67/6UOX9AwkoXDlF3nrwV/Ng33GnK0ejuhq8LMHu8u6IiStgLJi3Mh3yEUan8k+9tgEkB97426WR8g4ehW4jVYH+waky2vMK9jcRO6EO4vdJLUYhIEGhlBJoA21zmLXVhxXoGMUnOcCjwtqTNPVPfi70Tr/a3GurWs2mYyt+4vTCSdPxXHZkYSftPvGhB7Zs1LDWUet4whdNRj0FeCBAIUpnRq2IYclp5SC5Hm/MXzG3SQEi31aqLMtpPg1LO4A7TQDY/ioEx9xDboOKKDvXPnva+JZYWvGXbr1lMv0JDEz5sYmliEf0glRzvcNRxi0gv1aSopg2Ecs68NtIrzStQvlkqLCxEfFYk4Gz/pCIj8PMADCNblSys9oumN+DAvQJsGsur8m5feNtSlEVM4rHiuaysNp9pJ2zvuMLpOn1pbMIed5y81OL9+os5NtKyCDGuv0YdHWi8h57JcQWJHHRi8ZKLp/zYgo29eKkRXN64DzUxf5db3gBKr5harISmx7zOmjgHLRYu1qTzGVHmuIbKorttPSFW4Djx/LUutMmFM+7GN+0GiuYb3vO4/El9xrTYxo3EnPWQeN7r/2E79oeAJ7DB1Q9Xb72TjPQ2C4eyDzV9W65YWDlKeXUjN/0rdQgJN3U7Ji/dnwb3N+aUzmlvT6OTqBA=
