language: python
python:
- '3.6'
install:
- pip install -e .
script:
- python -c "import tinycards"
deploy:
  provider: pypi
  user: floscha
  password:
    secure: fGNlMnLPdmIUulX2oNQF4a78Utfce2Dg9Sld/EAyBkM5B0kz80SxrXHkOOdIfDyOwSnAJAf2nSJcGmbAH2ZfYdG6Bmyhl5ZgH8OzTqUbZdzym2gPKQ2z+aaqxZ0tXrEBMNm6oMhFAG47aPKWTiWynVa4KpYQnl6nfWxPZvdgK60a8WNXKnjgQd8/h6bW1SDb6wY/dy+TTQ5RGxqsqkwG9TuhmGCzopBLdnLhwHL3fr0XivWTqxxBOWvt5GS404X7MrGfjYvDQUYcaUfqDSvNXS5TNYMPBIfB2RumgLXqc7Z88vZ1j26yG364N/9WOOLINOxXkLVCl3+RRyzXGk30vQCN6VSVQe9vXH8XsrTZBepArOm2tYf2Su785pKQjQiC5KwsbWBbj9dS187yewXe5dL9mvwOTOxlzyiXJRgbt40htfYcnx6JrNc1sLxN9QYcGHhazkGh1FzAAcZL7RBazO86zMTP5zZuF16gI7kkMQdI0cj5y8LuN0T1TQ8pehH8kKkqVneJSGtKsLbRB6Sw6dl1iAyH2qKMcvpPk/kM+LzC8NGm1m4gGOBcLKgdb42xQSb5sq7hQrO4Zu0wt1xm3gpmpXD6Ncdx17ngQd1KqSCChoEe/ZWMks/j6wf7tQP/+vShQvyF461UzTYdbJdRijz0WKYDECIaAKsm2cN8SOc=
env:
  global:
  - TINYCARDS_IDENTIFIER=njam-test
  - TINYCARDS_PASSWORD=gRaVeATiod
  matrix:
  - secure: YtA+3hTUUXrWqUpknuPwUeA+E2mQVBxtpSpPphtwVJuvaFKTkkdj4rt2vKNKUrapguwNjAGiwJXKOyNxS+QG1KfE0O5uECHfEGDnM5kvOvoNX/Cql25HgzJaUA4MnOgVoxVb+5+CYqPHI21uE8I/jb7NrQ/Bu2xWh/i3OFP354Ni9aU//mGu7AKcaXxcFRLKbir4NFpjcJXvYzxselRtWLlrT1KpanBja/PubUvwuxpMuguVnY0QeOuDfRmasVUzya/uu7sBtHidbndm0Ca1PVaK/BtoFWP9hTHaJi5KWx4ihBIV6oXnZh3G9WSMo7PPMCiO1U0ppv/LFwENc+65QKd1ye1lQ8kgHh7esEPoRSE7ZgUQfxsYTaxNH7AUUTUhiRfdThc6KMxTC3bPDJL0lEpSADxq/t/ayQoDMgYTRZKpPx4vi1b4m75YlEsHuMfe9re9NXS/v34FUfdUrBL19i/SY6njAtUSbBmv/2sHanBw4C3CR9+yTTNKaDvJqAhUtJ4WWt4NizL51Ci4CXbOpSMMUQxzpOtE7vAF2jfUPrl2GtPD8z2PEcveb7ejFkmmINGFEADniILwrKmRiPKJcJDW+aH0+TdDSc7wOVx3RT4Y4LiWhTkakik6QB/cPZ+odoD5sWrW5CzWT227MBRnZ1doCrR0uzbbOKOZr/MrEno=
  - secure: hqD2YC6DOuSYsxCIVLRWEFFE1PthcQwp7ycIf2U7LPPybGDZxQM92UQYY6VIrwa0O3wpz3YRDzpmzf9nc8TkQkvVJT9Wp6/2H2wfZ+q7scqRBgbigwf10Zq5/1wZiwi+lorCaiceGkQ587MN+N3EE4meLB1hpepVWPu8peoH5kDh52V0w7cVzy0mFyHzDjyxupi8Y59HnzgHPBB8cDONxtqW9Crdy+QEiSM7cNdW0/pnLhO7B2ZHxn14/OW8WirbgYNvp/ArOvVWvnA+HJY4BtHJn1qWWL6hPpMYcf/dwdc3n0Q3Ns1dvsv9crKLL0d6O414YC2RXiml45Fxf2jKKgq/91JyTVjXA8DS5eeKYRnYBNxnZKLYedBq0khHRFDJSWSubLFRGgG7w1Tg/HztHF7LHu53JKzrjKBpTmquJA1lWU+mL5yReGjTsRBdkofScSrEgX/L7Z/jUN65taQ3FqbIKYfKBvuVTIkB4ogUEJDZl/0ZpWfyWNbRtHu8u9ytuA+B7pY6a2KtBTFEO4r0m26JMfVTdL74aVa1iFkkzycC3LUD1+RzVbV7V3E4LmiCQQRZSIGJXyd1VSuTpDClH6sj9r13kFPGtulby1jYJ5051JWfsrP4hG0i+kenZ7t3W/KY8mNGFTLhq3bggcbbmoHbyD9VSQ49/lLmtdxMdgA=
